services:
  - name: fhir-frontend
    type: web
    runtime: docker
    repo: https://github.com/yazan1kasem/FHIR.git
    branch: master
    region: frankfurt
    dockerContext: .
    dockerfilePath: ./spengerclient/Dockerfile
  - name: fhir-backend
    type: web
    runtime: docker
    repo: https://github.com/yazan1kasem/FHIR.git
    branch: master
    plan: starter
    region: frankfurt
    dockerfilePath: Dockerfile
  - type: pserv
    name: spengeronfhir
    runtime: docker
    repo: https://github.com/render-examples/mysql
    plan: starter
    branch: oh/mysql_8.0.24
    autoDeploy: true
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: root
      - key: MYSQL_PASSWORD
        value: root
      - key: MYSQL_USER
        value: root
      - key: MYSQL_DATABASE
        value: spengeronfhir
    region: frankfurt
    dockerContext: .
    dockerfilePath: ./Dockerfile
    disk:
      name: disk
      mountPath: /var/lib/mysql
      sizeGB: 10
